language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.3.1

before_script:
  - yarn global add webpack

script:
  - yarn test

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
