language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
