# Site settings
title: Iago Dahlem Lorensini
email: iagodahlemlorensini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Front-end Developer current working at Codeminer42.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iagodahlem.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iagodahlem
github_username:  iagodahlem
author: Iago Dahlem Lorensini

# Build settings
markdown: kramdown

permalink: /:title/

exclude:
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock

sass:
  style: :compressed
